import AdminNavbar from "@/components/adminNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
      <div>
        <AdminNavbar />
        <div>{children}</div>
      </div>
    </body>
  );
}
